#!/usr/bin/env python
import logging
import os

def main():
    jobname = None
    
    if 'JOB_NAME' in os.environ:
        jobname=os.environ['JOB_NAME']
    if jobname == None:
        log.error("No JOB_NAME Enviroment variable set")
        sys.exit(2)
    log.info("JOB_NAME=%s" % jobname )

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    main()
